version: '3.8'

services:

  todoback:
    build: ./todo-app/back-end/
    ports:
      - 3001:3001
    networks:
      - network-1

  todofront:
    build: ./todo-app/front-end/
    ports:
      - 3000:3000
    depends_on:
      - todoback
    environment:
      - REACT_APP_API_HOST=todoback
    networks:
      - network-1

  todotests:
    build: ./todo-app/tests/
    depends_on:
      - todofront
      - todoback
    environment:
      - FRONT_HOST=todofront
    networks:
      - network-1

networks:
  network-1:
